spring:
  application:
    name: commons
logging:
  level:
    root: info
    org.springframework.web: info
    org.springframework.web.reactive: info
    your.package.name: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trace=%X{traceId:-} span=%X{spanId:-}] [%X{correlationId}] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [trace=%X{traceId:-} span=%X{spanId:-}] [%X{correlationId}] %-5level %logger{36} - %msg%n"
  file:
    name: logs/application.log

  webflux:
    context-path: /api
  logback:
    rollingpolicy:
      max-file-size: 10MB
      max-history: 30
      total-size-cap: 3GB
